---
- name: Copy files from local to remote host
  hosts: web

  tasks:
  - name: Copying file
    become: true
    copy:
     src: /home/ubuntu/anible-devops/file.txt
     dest: /home/ec2-user/
     owner: ec2-user
     group: ec2-user
     mode: 0644
  
  - name: File permissions
    file:
     path: /home/ec2-user/file.txt
     mode: a+w